# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      compose:
        patterns:
          - "androidx.compose*"
          - "androidx.constraintlayout:constraintlayout-compose*"
    commit-message:
      prefix: "deps(gradle)"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/*"
    groups:
      github-actions:
        patterns:
          - "*"
        group-by: "dependency-name"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(github-actions)"
