# $schema: https://json.schemastore.org/github-workflow.json
name: check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: check-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - uses: reviewdog/action-setup@v1
      - name: run android lint
        shell: bash
        run: |
          ./gradlew :auto-mutton-recipe-compose:lintDebug
          ./gradlew :auto-mutton-recipe-compose:samples:lintDebug
          ./gradlew :auto-mutton-recipe-savedstate:lintDebug
      - name: run detekt
        shell: bash
        run: |
          ./gradlew detekt
      - name: run reviewdog review
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat auto-mutton-recipe-compose/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="compose android lint" -reporter=github-pr-review;
          cat auto-mutton-recipe-compose/samples/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="compose samples android lint" -reporter=github-pr-review;
          cat auto-mutton-recipe-savedstate/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="savedstate android lint" -reporter=github-pr-review;
          cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter=github-pr-review;
      - name: run reviewdog suggest
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew :auto-mutton-recipe-compose:lintFix :auto-mutton-recipe-compose:samples:lintFix :auto-mutton-recipe-savedstate:lintFix detekt -PautoCorrect --quiet --continue || true;
          TMPFILE=$(mktemp);
          git diff >"${TMPFILE}";
          git stash -u || git stash drop;
          cat "${TMPFILE}" | reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review;

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: check api file
        shell: bash
        run: |
          ./gradlew apiCheck

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: publish
        shell: bash
        run: |
          ./gradlew publishAllPublicationsToLocalRepository --no-configuration-cache

  test-linux-x64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [
          "jvm",
          "linuxX64",
          "jsNode",
          "jsBrowser",
          "wasmJsNode",
          "wasmWasi",
          "testDebugUnit",
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: test
        shell: bash
        run: |
          ./gradlew ${{ matrix.module }}Test
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: unit-test-result-${{ matrix.module }}
          path: '**/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false

  test-mac-x64:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        module: [
          "iosX64",
          "tvosX64",
          "watchosX64",
          "macosX64",
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: test
        shell: bash
        run: |
          ./gradlew ${{ matrix.module }}Test
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: unit-test-result-${{ matrix.module }}
          path: '**/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false

  test-mac-arm64:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        module: [
          "iosSimulatorArm64",
          "tvosSimulatorArm64",
          "watchosSimulatorArm64",
          "macosArm64",
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: test
        shell: bash
        run: |
          ./gradlew ${{ matrix.module }}Test
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: unit-test-result-${{ matrix.module }}
          path: '**/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false

  test-win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        module: [
          "mingwX64",
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: test
        shell: bash
        run: |
          ./gradlew ${{ matrix.module }}Test
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: unit-test-result-${{ matrix.module }}
          path: '**/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false
