# $schema: https://json.schemastore.org/github-workflow.json
name: check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: check-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - uses: reviewdog/action-setup@v1
      - name: run android lint
        shell: bash
        run: |
          ./gradlew lintDebug
      - name: run detekt
        shell: bash
        run: |
          ./gradlew detekt
      - name: run reviewdog review
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat auto-mutton-recipe-compose/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="compose android lint" -reporter=github-pr-review;
          cat auto-mutton-recipe-compose/samples/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="compose samples android lint" -reporter=github-pr-review;
          cat auto-mutton-recipe-savedstate/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="savedstate android lint" -reporter=github-pr-review;
          cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter=github-pr-review;
      - name: run reviewdog suggest
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew lintFix detekt -PautoCorrect --quiet --continue || true;
          TMPFILE=$(mktemp);
          git diff >"${TMPFILE}";
          git stash -u || git stash drop;
          cat "${TMPFILE}" | reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review;

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: check api file
        shell: bash
        run: |
          ./gradlew apiCheck

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: publish
        shell: bash
        run: |
          ./gradlew publishAllPublicationsToLocalRepository --no-configuration-cache

  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: dokka
        shell: bash
        run: |
          ./gradlew dokkaHtmlMultiModule --no-build-cache --no-configuration-cache

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: testDebugUnitTest
            os: ubuntu-latest
          - task: jvmTest
            os: ubuntu-latest
          - task: desktopTest
            os: ubuntu-latest
          - task: linuxX64Test
            os: ubuntu-latest
          - task: jsNodeTest
            os: ubuntu-latest
          - task: jsBrowserTest
            os: ubuntu-latest
          - task: wasmJsNodeTest
            os: ubuntu-latest
          - task: wasmWasiTest
            os: ubuntu-latest
          - task: iosX64Test
            os: macos-13
          - task: tvosX64Test
            os: macos-13
          - task: watchosX64Test
            os: macos-13
          - task: macosX64Test
            os: macos-13
          - task: iosSimulatorArm64Test
            os: macos-latest
          - task: tvosSimulatorArm64Test
            os: macos-latest
          - task: watchosSimulatorArm64Test
            os: macos-latest
          - task: macosArm64Test
            os: macos-latest
          - task: mingwX64Test
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/java
      - uses: ./.github/actions/konan
      - uses: ./.github/actions/gradle
      - name: test
        shell: bash
        run: |
          ./gradlew ${{ matrix.task }}
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: unit-test-result-${{ matrix.task }}
          path: '**/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false
