# $schema: https://json.schemastore.org/github-workflow.json
name: deploy dokka content to Pages

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+[0-9]+"
  workflow_dispatch:

concurrency:
  group: pages-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - uses: actions/configure-pages@v5
      - name: build html
        shell: bash
        run: |
          ./gradlew dokkaHtmlMultiModule --no-build-cache --no-configuration-cache
      - uses: actions/upload-pages-artifact@v4
        with:
          path: './build/dokka/htmlMultiModule'
      - uses: actions/deploy-pages@v4
        id: deployment
